name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: 

permissions:
  contents: write # 赋予默认 GITHUB_TOKEN 创建 Release 的权限

jobs:
  release-zip:
    runs-on: ubuntu-latest # 使用 ubuntu 比 macos 速度更快且免费额度更多

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
      - name: Install and Build
        run: |
          pnpm install
          NUXT_APP_BASE_URL='./' pnpm generate
          
      - name: Create Zip Archive
        # 如果是构建产物，这里把产物目录（如 .output/public）打包
        run: zip -r release.zip .output/public

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          tag_name: "v1.243.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
